/* Створення таблиці Користувачів */
create table Users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20),
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    /* Обмеження первинного ключа */
    CONSTRAINT pk_users PRIMARY KEY (user_id),

    /* Обмеження унікальності */
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_username UNIQUE (username),

    /* Обмеження з Регулярними Виразами (Regex) */
    CONSTRAINT chk_email_format CHECK (
        email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
    ),

    CONSTRAINT chk_phone_format CHECK (
        phone_number ~* '^\+?[0-9]{10,15}$'
    )
);

/* Створення таблиці Сигналів Тривоги */
CREATE TABLE alerts (
    alert_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    alert_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    gps_location VARCHAR(100) NOT NULL,
    status VARCHAR(20) DEFAULT 'new',

    CONSTRAINT pk_alerts PRIMARY KEY (alert_id),

    /* Обмеження зовнішнього ключа */
    CONSTRAINT fk_alerts_user FOREIGN KEY (user_id)
    REFERENCES users (user_id) ON DELETE CASCADE
);

/* Створення таблиці Вокальних Записів */
CREATE TABLE vocal_recordings (
    recording_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    filename VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_vocal PRIMARY KEY (recording_id),
    CONSTRAINT fk_vocal_user FOREIGN KEY (user_id)
    REFERENCES users (user_id) ON DELETE CASCADE
);
